window.EATWHAT_DATA = {
  dishes: {
    Chinese:['Mapo tofu','Dan dan noodles','Salt and pepper squid','Beef chow fun','Kung pao chicken','Char siu pork','Wonton soup','Hot and sour soup','Twice-cooked pork','Sichuan eggplant','Xiao long bao','Scallion pancakes','Peking duck','Sweet and sour pork','Congee','Fried rice','Cantonese steamed fish','Ma po aubergine','Biang biang noodles','Chinese broccoli with oyster sauce'],
    Vietnamese:['Pho bo','Banh mi','Bun cha','Fresh rice-paper rolls','Bun bo Hue','Com tam','Cao lau','Banh xeo','Caramelised pork','Lemongrass chicken','Vietnamese chicken salad','Beef vermicelli bowl','Banh cuon','Canh chua','Vietnamese pancakes','Grilled pork skewers','Cha ca','Bun rieu','Claypot fish','Vietnamese iced coffee'],
    Japanese:['Chicken katsu curry','Okonomiyaki','Miso eggplant','Yakisoba','Tonkotsu ramen','Teriyaki salmon','Karaage chicken','Onigiri','Gyoza','Sushi rolls','Udon noodle soup','Soba noodles','Chirashi bowl','Tamagoyaki','Miso soup','Agedashi tofu','Japanese curry','Takoyaki','Mochi','Matcha tiramisu'],
    Korean:['Bibimbap','Korean fried chicken','Japchae','Kimchi jjigae','Bulgogi','Tteokbokki','Sundubu jjigae','Kimchi fried rice','Kimbap','Dakgalbi','Galbi','Korean pancakes','Jajangmyeon','Bossam','Doenjang jjigae','Mandu','Korean corn dogs','Spicy pork','Gyeran mari','Bingsu'],
    Indian:['Butter chicken','Palak paneer','Chana masala','Biryani','Tikka masala','Dal makhani','Rogan josh','Aloo gobi','Korma','Samosas','Naan','Dosa','Idli sambar','Vindaloo','Malai kofta','Prawn curry','Tandoori chicken','Pav bhaji','Rajma','Gulab jamun'],
    Italian:['Mushroom risotto','Margherita pizza','Gnocchi al pesto','Eggplant parmigiana','Spaghetti carbonara','Lasagne','Osso buco','Pasta puttanesca','Cacio e pepe','Ravioli','Arancini','Focaccia','Minestrone','Polenta','Tiramisu','Panna cotta','Cannoli','Pasta e fagioli','Pesto pasta','Calzone'],
    Greek:['Chicken souvlaki','Moussaka','Spanakopita','Lemon potatoes','Greek salad','Gyros','Pastitsio','Dolmades','Keftedes','Tiropita','Fasolada','Gigantes plaki','Saganaki','Tzatziki','Horiatiki','Greek lamb roast','Kolokithokeftedes','Avgolemono soup','Baklava','Loukoumades'],
    Thai:['Pad thai','Green curry','Massaman beef','Larb salad','Tom yum','Red curry','Pad see ew','Pad kra pao','Som tam','Panang curry','Khao soi','Thai basil chicken','Mango sticky rice','Thai fish cakes','Satay chicken','Jungle curry','Crying tiger beef','Tom kha gai','Coconut rice','Thai roti'],
    Mexican:['Chicken tacos','Vegetable enchiladas','Fish tacos','Chilaquiles','Burritos','Quesadillas','Pozole','Tamales','Carnitas','Tostadas','Nachos','Elote','Guacamole','Mole chicken','Fajitas','Huevos rancheros','Sopes','Taquitos','Mexican rice','Tres leches cake'],
    'Middle Eastern':['Chicken shawarma','Falafel plate','Shakshuka','Mujadara','Hummus','Baba ganoush','Tabbouleh','Fattoush','Kofta','Manakish','Kibbeh','Fatteh','Lamb kebabs','Labneh','Freekeh salad','Musakhan','Mansaf','Za’atar flatbread','Baklava','Kunafa'],
    French:['Ratatouille','Croque monsieur','French onion soup','Crêpes','Boeuf bourguignon','Coq au vin','Quiche Lorraine','Cassoulet','Duck confit','Steak frites','Salade Niçoise','Soufflé','Tarte tatin','Crème brûlée','Chocolate mousse','Madeleines','Profiteroles','Croissants','Pain perdu','Clafoutis'],
    Australian:['Chicken parmigiana','Barramundi and chips','Meat pie','Roast lamb','Sausage sizzle','Vegemite toast','Damper','ANZAC biscuits','Lamingtons','Pavlova','Beef burger','Fish and chips','Chicken schnitzel','Salt and pepper squid','Aussie breakfast','Kangaroo steak','Beetroot salad','Pumpkin scones','Potato scallops','Vanilla slice'],
    Vegetarian:['Chickpea curry','Mushroom tacos','Pumpkin risotto','Veggie ramen','Lentil bolognese','Cauliflower wings','Stuffed capsicums','Vegetable lasagne','Tofu stir-fry','Falafel wraps','Black bean burgers','Paneer tikka','Vegetable paella','Broccoli pasta','Sweet potato chilli','Eggplant curry','Spinach pie','Mushroom bourguignon','Zucchini fritters','Tomato galette'],
    Sweet:['Chocolate brownies','Apple crumble','Mango sticky rice','Sticky date pudding','Cheesecake','Chocolate chip cookies','Banana bread','Lemon tart','Carrot cake','Cinnamon rolls','Eton mess','Pavlova','Ice cream sundae','Rice pudding','Bread and butter pudding','Donuts','Churros','Banoffee pie','Peach cobbler','Victoria sponge']
  },
  restaurants: {
    'Fast food':['Guzman y Gomez Rundle Mall','Guzman y Gomez Hindley Street','Nordburger Hindley Street','Nordburger Norwood','Betty’s Burgers Rundle Mall','Betty’s Burgers Norwood','Fugazzi Bar & Dining takeaway','Nando’s Rundle Mall','Nando’s North Adelaide','Oporto Rundle Mall','Hungry Jack’s Rundle Mall','McDonald’s Rundle Mall','KFC Rundle Mall','Subway Rundle Mall','Salsas Fresh Mex Glenelg','Schnitz Rundle Mall','Roll’d Rundle Mall','Lord of the Fries Rundle Mall','Chicken Cave Prospect','Burger Republic Unley'],
    Casual:['Sunny’s Pizza','Lucia’s Pizza & Spaghetti Bar','Parwana Afghan Kitchen','Osteria Oggi','Tony Tomatoes','Etica','Pizza e Mozzarella Bar','Nido Bar & Pasta','Antica Pizzeria','Bottega Bandito','The Flying Fig Deli','Bread & Bone','The Stag Public House','The Cumby','The Exeter','The Original Pancake Kitchen','Est Pizzeria','Midnight Spaghetti','Latteria','The Pasta Deli'],
    'Fine dining':['Restaurant Botanic','Africola','Arkhe','Fino Vino','Magill Estate Restaurant','Penfolds Magill Estate Kitchen','Garcon Bleu','Shobosho','Tasting Australia Restaurant','Restaurant Orana','The Peak at Mt Lofty','Georges on Waymouth','The Lane Vineyard Restaurant','Hardy’s Verandah Restaurant','The Playford Restaurant','Lenzerheide Restaurant','Chianti','Jolley’s Boathouse','Mayflower Restaurant','The River Café'],
    Cafe:['Peter Rabbit','Crack Kitchen','Exchange Specialty Coffee','My Kingdom for a Horse','Please Say Please','Mylk Bar','Mister Sunshine’s','Coffee Branch','Sazon Espresso','The Pantry on Egmont','C.R.E.A.M.','Hey Jupiter','Sublime Café','Whistle & Flute','The Loose Caboose','Melt Hyde Park','Argo on the Parade','Café Troppo','Pollen 185','Avenues Café Bar'],
    Asian:['Golden Boy','Concubine','Vietnam Restaurant','K-Pub','Izakaya Doma','Ying Chow','Madame Hanoi','Gin Long Canteen','Soonta','Mandoo','Gogi Korean BBQ','Ba Guo Bu Yi','Ding Hao','Hawker Chan','Little NNQ','K-pub BBQ','Shiki Japanese Restaurant','K-BBQ','Hotpot House','Star Dumplings'],
    Vegetarian:['Greenhouse on Gilbert','Two-Bit Villains','Veggie Vie','Vegan & Co','Thea Tea Shop','Nagev','The Rose East End','Cherry Darlings Bakehouse','Sassy Monkey','The Coffee Institute','The Greek on Halifax vegetarian menu','Namaste Nepal vegetarian menu','Laksa House vegetarian menu','Chatkazz vegetarian menu','Chutney vegetarian menu','Beyond India vegetarian menu','Ragini Spice vegetarian menu','Raj on Taj vegetarian menu','Thea Vegetarian Tea House','Plant 3 Bowden'],
    'Drinks & bites':['Malt Shovel Taphouse','Maybe Mae','Hains & Co','Proof Bar','Bank Street Social','Clever Little Tailor','Pink Moon Saloon','The Bibliotheca Bar & Book Exchange','BRKLYN','Nola','Electra House','The Howling Owl','Udaberri','La Buvette','Bar Peripheral','Golden North','The Gilbert Street Hotel','The Exeter Hotel','The King\'s Head','The Wheatsheaf Hotel'],
    'All Adelaide picks':['The Greek on Halifax','Barnacle Bill','Junction Australia','Fishbank','Sean’s Kitchen','Ayers House','Koomo','Kafana','The Parkside Hotel','The Lion Hotel','The Bath Hotel','The Duke of York','The Kent Town Hotel','The Unley','The Colonist','The Norwood Hotel','The Strand','Hains & Co','Daughter in Law','Soi 38']
  }
};
